version: '3.8'

services:
  rails:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - "./back:/rails"
    ports:
      - "3005:3005"
    environment:
      - RAILS_ENV=development
    depends_on:
      - postgres

  react:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - "./front:/app"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
